version: "3.7"

services: 
    mysql:
      image: mysql:5.7
      container_name: ejercicio7-db
      restart: unless-stopped
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - 3306:3306
      volumes:
        - db-data7:/var/lib/mysql
      environment: 
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: ejercicio7
        MYSQL_USER: ejercicio7
        MYSQL_PASSWORD: secret
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links: 
            - mysql:db
        ports: 
            - 8081:80

volumes: 
  db-data7: