version: "3.7"

services:
    node:
      build:
        context: ./
        dockerfile: Dockerfile
      volumes:
        - .:/src
      command: node server
      ports:
        - "3000:3000"
    mysql:
      image: mysql:5.7
      container_name: ejercicio1-db
      restart: unless-stopped
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - 3306:3306
      volumes:
        - db-data:/var/lib/mysql
      environment: 
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: ejercicio1
        MYSQL_USER: ejercicio1
        MYSQL_PASSWORD: secret
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links: 
            - mysql:db
        ports: 
            - 8081:80

volumes: 
  db-data: